import {
SquaresFour as LayoutDashboard,
  Users,
  CalendarBlank as CalendarIcon,
  Plus,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  X,
  CheckCircle as CheckCircle2,
  Circle,
  ArrowSquareOut as ExternalLink,
  Briefcase,
  UserCircle as UserCircle2,
  SpinnerGap as Loader2,
  Trash as Trash2,
  VideoCamera as Video,
  ArrowRight,
  UserPlus,
  MonitorPlay,
  MagnifyingGlass as Search,
  List as Menu,
  PenNib as PenTool,
  ListBullets as LayoutList,
  CalendarDots as CalendarDays,
  Warning as AlertTriangle,
  Smiley as Smile,
  SmileyMeh as Meh,
  SmileySad as Frown,
  Sticker,
  InstagramLogo as Instagram,
  PencilSimple as Edit,
  Tray as Inbox,
  Moon,
  Sun,
  CursorClick as MousePointerClick,
  Fire as Flame,
  TreeStructure as ListTree,
  CaretDown as ChevronDown,
  CaretUp as ChevronUp,
  Sparkle as Sparkles,
  Trophy,
  Medal,
  ChartBar as BarChart3,
  ShieldCheck,
  SignIn as LogIn,
  SignOut as LogOut,
  ClipboardText as ClipboardList,
  Lock,
  Envelope as Mail,
  TextAlignLeft as AlignLeft,
  Calendar,
  CalendarX as CalendarOff,
  CalendarPlus,
  CalendarDots as CalendarRange,
  Check,
  CheckSquare,
  Clock,
  FileText,
  ChatText as MessageSquare,
  Pencil,
  Play,
  FloppyDisk as Save,
  PaperPlaneTilt as Send,
  Square,
  Timer,
  User,
  UserMinus as UserX,
  Lightning as Zap,
  PauseCircle,
  DotsThree as MoreHorizontal,
  DotsSixVertical as GripVertical,
  Paperclip,
  Microphone,
  Image as ImageIcon,
  Stop,
  FilePlus,
  PushPin as PinIcon,
  ArrowBendUpLeft as ReplyIcon,
  Phone,
  VideoCamera,
  ThumbsUp,
  Heart,
  Eye,
  Bell,
  BellSlash,
} from "@phosphor-icons/react";

export const IconsMap = {
  LayoutDashboard,
  Users,
  CalendarIcon,
  Plus,
  ChevronLeft,
  ChevronRight,
  X,
  CheckCircle2,
  Circle,
  ExternalLink,
  Briefcase,
  UserCircle2,
  Loader2,
  Trash2,
  Video,
  ArrowRight,
  UserPlus,
  MonitorPlay,
  Search,
  Menu,
  PenTool,
  LayoutList,
  CalendarDays,
  AlertTriangle,
  Smile,
  Meh,
  Frown,
  Sticker,
  Instagram,
  Edit,
  Inbox,
  Moon,
  Sun,
  MousePointerClick,
  Flame,
  ListTree,
  ChevronDown,
  ChevronUp,
  Sparkles,
  Trophy,
  Medal,
  BarChart3,
  ShieldCheck,
  LogIn,
  LogOut,
  ClipboardList,
  Lock,
  Mail,
  AlignLeft,
  Calendar,
  CalendarOff,
  CalendarPlus,
  CalendarRange,
  Check,
  CheckSquare,
  Clock,
  FileText,
  MessageSquare,
  Pencil,
  Play,
  Save,
  Send,
  Square,
  Timer,
  User,
  UserX,
  Zap,
  PauseCircle,
  MoreHorizontal,
  GripVertical,
  Paperclip,
  Microphone,
  Image: ImageIcon,
  Stop,
  FilePlus,
  Pin: PinIcon,
  Reply: ReplyIcon,
  Phone,
  VideoCamera,
  ThumbsUp,
  Heart,
  Eye,
  Bell,
  BellSlash,
};

export const Icon = ({ name, size = 18, className = "", ...props }) => {
  const PhosphorIcon = IconsMap[name];
  const {
    "aria-hidden": ariaHidden = true,
    focusable = false,
    ...iconProps
  } = props;
  return PhosphorIcon ? (
    <PhosphorIcon
      size={size}
      weight="bold"
      className={className}
      aria-hidden={ariaHidden}
      focusable={focusable}
      {...iconProps}
    />
  ) : null;
};
